spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_db
spring.datasource.username=root
spring.datasource.password=Password@mysql
jwt.secret=ThisIsASecretKeyThatIsAtLeast32CharactersLongForHS256
spring.jpa.open-in-view=false
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true